spring:
  application:
    name: api-gateway

server:
  port: 9000

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: '${EUREKA_ENV_NET:http://localhost:8761}/eureka'
    fetch-registry: true
    register-with-eureka: true

ribbon:
  ReadTimeout: 5000
